name: Build Extensions

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Providers
        run: ./gradlew :TelegramProvider:make :GoogleDriveProvider:make

      - name: Generate repo.json and plugins.json
        run: |
          mkdir -p builds

          echo '{
            "name": "cloudestrem-extension-deepu",
            "iconUrl": "https://bollywood.eu.org/favicon.ico",
            "description": "Telegram Extension",
            "manifestVersion": 1,
            "pluginLists": [
              "https://raw.githubusercontent.com/deepu2135/cloudestrem-extension-deepu/builds/plugins.json?v=3"
            ]
          }' > builds/repo.json

          echo '[
            {
              "name": "Telegram",
              "internalName": "TelegramProvider",
              "url": "https://raw.githubusercontent.com/deepu2135/cloudestrem-extension-deepu/builds/TelegramProvider.cs3?v=14",
              "tvTypes": ["Movie", "TvSeries"],
              "language": "en",
              "iconUrl": "https://raw.githubusercontent.com/deepu2135/cloudestrem-extension-deepu/master/icon.png",
              "apiVersion": 10,
              "version": 164,
              "authors": ["deepu2135"],
              "status": 1,
              "description": "Stream any media from your Telegram chats and channels on-demand"
            },
            {
              "name": "Google Drive",
              "internalName": "GoogleDriveProvider",
              "url": "https://raw.githubusercontent.com/deepu2135/cloudestrem-extension-deepu/builds/GoogleDriveProvider.cs3?v=14",
              "tvTypes": ["Movie", "TvSeries"],
              "language": "en",
              "iconUrl": "https://raw.githubusercontent.com/deepu2135/cloudestrem-extension-deepu/master/google_drive_icon.png",
              "apiVersion": 10,
              "version": 12,
              "authors": ["deepu2135"],
              "status": 1,
              "description": "Stream video and audio from your Google Drive"
            }
          ]' > builds/plugins.json

      - name: Push to builds branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git checkout -B builds
          git rm -rf .github/ || true
          cp -r builds/. .
          git add -f repo.json plugins.json *.cs3 || true
          git status
          git commit -m "Update builds" || true
          git push origin builds --force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TelegramProvider
          path: builds/
